vsphere_server   = "vcsa.kazmi.lab"
vsphere_user     = "Administrator@vsphere.local"
datacenter       = "LabDatacenter"
cluster          = "Lab Cluster"
datastore        = "iSCSI-Datastore"
network_name     = "vData"
builder_ipv4     = "10.0.0.50"
ssh_username     = "root"